# Generated by Django 4.2.13 on 2026-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Analytics access',
                'verbose_name_plural': 'Analytics access',
                'permissions': [('view_analyticsdashboard', 'Can view analytics dashboard')],
                'managed': True,
            },
        ),
    ]
