# Generated by Django 4.2.28 on 2026-02-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('stream', models.CharField(max_length=50)),
                ('min_education', models.CharField(blank=True, max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('growth_outlook', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'careers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StreamRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_stream', models.CharField(max_length=50)),
                ('secondary_stream', models.CharField(blank=True, max_length=50)),
                ('tertiary_stream', models.CharField(blank=True, max_length=50)),
                ('scores', models.JSONField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_recommendation', to='assessments.assessmentattempt')),
            ],
            options={
                'db_table': 'stream_recommendations',
            },
        ),
        migrations.CreateModel(
            name='CareerCategoryWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_weights', to='careers.career')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_weights', to='assessments.category')),
            ],
            options={
                'db_table': 'career_category_weights',
            },
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['stream'], name='careers_stream_439bed_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['is_active'], name='careers_is_acti_c4cbef_idx'),
        ),
        migrations.AddIndex(
            model_name='careercategoryweight',
            index=models.Index(fields=['career'], name='career_cate_career__91abf3_idx'),
        ),
        migrations.AddIndex(
            model_name='careercategoryweight',
            index=models.Index(fields=['category'], name='career_cate_categor_d28da1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careercategoryweight',
            unique_together={('career', 'category')},
        ),
    ]
