# Generated by Django 4.2.28 on 2026-02-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='education_cost_tier',
            field=models.CharField(choices=[('low', 'Low (govt colleges, vocational)'), ('medium', 'Medium (private degree)'), ('high', 'High (MBBS, IIT, premium courses)')], default='medium', max_length=20),
        ),
        migrations.CreateModel(
            name='CareerSubjectWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_slug', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_weights', to='careers.career')),
            ],
            options={
                'db_table': 'career_subject_weights',
                'indexes': [models.Index(fields=['career'], name='career_subj_career__3c6ad8_idx')],
                'unique_together': {('career', 'subject_slug')},
            },
        ),
    ]
