# Generated by Django 4.2.13 on 2026-04-11 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_add_visitor_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=16)),
                ('exception_class', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('traceback_text', models.TextField(blank=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API error log',
                'verbose_name_plural': 'API error logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'exception_class'], name='common_apie_created_e4ff29_idx')],
            },
        ),
    ]
