# Generated by Django 4.2.28 on 2026-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='financial_tier',
            field=models.CharField(blank=True, choices=[('low', 'Limited (need scholarships/vocational options)'), ('medium', 'Moderate (can afford degree courses)'), ('high', 'Comfortable (can afford premium education)'), ('prefer_not', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='subject_marks',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'math': 85, 'science': 82, 'english': 78, 'social_science': 75}"),
        ),
    ]
