# Generated by Django 4.2.28 on 2026-02-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_id', models.PositiveIntegerField()),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='assessments.assessmentattempt')),
            ],
            options={
                'db_table': 'career_recommendations',
                'ordering': ['attempt', 'rank'],
                'indexes': [models.Index(fields=['attempt'], name='career_reco_attempt_90b6a3_idx')],
            },
        ),
    ]
