# Generated by Django 4.2.13 on 2026-03-02 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0002_add_financial_marks_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TraitScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(choices=[('analytical_reasoning', 'Analytical Reasoning'), ('quantitative_comfort', 'Quantitative Comfort'), ('creativity_innovation', 'Creativity & Innovation'), ('verbal_communication', 'Verbal & Communication'), ('social_orientation', 'Social Orientation'), ('leadership_drive', 'Leadership Drive'), ('risk_appetite', 'Risk Appetite'), ('structure_discipline', 'Structure & Discipline')], max_length=30)),
                ('raw_score', models.FloatField(default=0)),
                ('normalized_score', models.FloatField(default=0, help_text='0-10 scale')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_scores', to='game_assessment.gamesession')),
            ],
            options={
                'unique_together': {('session', 'trait_name')},
            },
        ),
        migrations.CreateModel(
            name='GameEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(choices=[('logic', 'Logic & Pattern Challenge'), ('risk', 'Risk & Leadership Simulator'), ('planner', 'Planner & Organization Game'), ('scenario', 'Scenario Section')], max_length=30)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game_assessment.gamesession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'game_name'], name='game_assess_session_d900d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameCareerTraitWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait_name', models.CharField(choices=[('analytical_reasoning', 'Analytical Reasoning'), ('quantitative_comfort', 'Quantitative Comfort'), ('creativity_innovation', 'Creativity & Innovation'), ('verbal_communication', 'Verbal & Communication'), ('social_orientation', 'Social Orientation'), ('leadership_drive', 'Leadership Drive'), ('risk_appetite', 'Risk Appetite'), ('structure_discipline', 'Structure & Discipline')], max_length=30)),
                ('weight', models.FloatField(default=0, help_text='0.0 to 1.0 — how important this trait is for the career')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_trait_weights', to='careers.career')),
            ],
            options={
                'unique_together': {('career', 'trait_name')},
            },
        ),
        migrations.CreateModel(
            name='CareerMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_matches', to='careers.career')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_matches', to='game_assessment.gamesession')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('session', 'career')},
            },
        ),
    ]
