# Generated by Django 4.2.13 on 2026-03-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=299, help_text='Amount in INR')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_orders', to='game_assessment.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'session')},
            },
        ),
    ]
