# Generated by Django 4.2.13 on 2026-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0002_reportorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
