# Generated by Django 4.2.13 on 2026-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0003_add_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportorder',
            name='amount',
            field=models.PositiveIntegerField(default=49, help_text='Amount in INR'),
        ),
    ]
