# Generated by Django 4.2.13 on 2026-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0004_report_price_default_49'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='assessment_tier',
            field=models.CharField(choices=[('free', 'Free overview'), ('premium', 'Full profile')], db_index=True, default='free', max_length=20),
        ),
    ]
