# Generated by Django 4.2.13 on 2026-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0005_assessment_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='premium_extension_complete',
            field=models.BooleanField(default=False, help_text='True after user completes premium-only questions and rescoring.'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='premium_unlocked',
            field=models.BooleanField(default=False, help_text='True after ₹99 premium bundle payment (before extra questions).'),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='product_type',
            field=models.CharField(choices=[('report', 'Career report (30Q)'), ('premium_bundle', 'Premium assessment + report')], db_index=True, default='report', max_length=20),
        ),
    ]
