# Generated by Django 4.2.29 on 2026-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0006_premium_bundle_and_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportorder',
            name='product_type',
            field=models.CharField(choices=[('report', 'Career report (Phase 1)'), ('premium_bundle', 'Premium extension + report')], db_index=True, default='report', max_length=20),
        ),
    ]
