# Generated by Django 4.2.13 on 2026-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_assessment', '0007_alter_reportorder_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportorder',
            name='upgrade_razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='upgrade_razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
