# Generated by Django 4.2.13 on 2026-04-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_assessment', '0008_report_order_upgrade_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Stored uppercase. Shown to users as entered.', max_length=40, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(help_text='0–100. Use 100 for a fully free checkout (no Razorpay charge).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='If set, code is not valid before this instant (UTC).', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='If set, code is not valid after this instant (UTC).', null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited total uses.', null=True)),
                ('max_redemptions_per_user', models.PositiveSmallIntegerField(default=1, help_text='How many successful checkouts per user can apply this code.')),
                ('internal_note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Payment coupon',
                'verbose_name_plural': 'Payment coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reportorder',
            name='pending_checkout_kind',
            field=models.CharField(blank=True, default='', help_text='initial | upgrade — matches CouponRedemption.context', max_length=16),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='pending_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='pending_final_amount_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='pending_list_price_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportorder',
            name='pending_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_orders', to='game_assessment.paymentcoupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(choices=[('initial', 'Initial purchase'), ('upgrade', 'Premium bundle upgrade')], max_length=16)),
                ('list_price_inr', models.PositiveIntegerField()),
                ('final_amount_inr', models.PositiveIntegerField()),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='game_assessment.paymentcoupon')),
                ('report_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='game_assessment.reportorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon redemption',
                'verbose_name_plural': 'Coupon redemptions',
                'ordering': ['-created_at'],
                'unique_together': {('report_order', 'context')},
            },
        ),
    ]
