# Generated by Django 4.2.13 on 2026-04-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_assessment', '0009_payment_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCounselingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_requests', to='game_assessment.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_counseling_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career counseling request',
                'verbose_name_plural': 'Requested counselings',
                'ordering': ['-created_at'],
            },
        ),
    ]
