# Generated by Django 4.2.28 on 2026-02-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='assessments.question'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['attempt'], name='user_respon_attempt_09954a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'is_active'], name='questions_categor_3b56e5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='questions_order_2c3df8_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['attempt'], name='assessment__attempt_1724c5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user'], name='assessment__user_id_2e7919_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'is_complete'], name='assessment__user_id_e297da_idx'),
        ),
        migrations.AddIndex(
            model_name='answeroption',
            index=models.Index(fields=['question'], name='answer_opti_questio_722681_idx'),
        ),
    ]
