# Generated by Django 4.2.13 on 2026-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_metadata_answeroption_category_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='api_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='premium_only',
            field=models.BooleanField(default=False, help_text='If true, only shown after premium unlock (Phase 2 extension).'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['code'], name='questions_code_c58a75_idx'),
        ),
    ]
